# Site settings
title: Matroska Specification
email: 
description:
baseurl: "/matroska-specification"
url:
twitter_username: 
github_username: 

# Build settings
markdown: kramdown

exclude: ["ebml_matroska_elements4rfc.md", "draft-lhomme-cellar-matroska-03.html", "draft-lhomme-cellar-matroska-03.xml", "draft-lhomme-cellar-matroska-03.txt", "draft-lhomme-cellar-matroska-03.html"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
